export HISTCONTROL="ignorespace:erasedups"

function has() {
  type "$1" > /dev/null 2>&1
}

function try_to_source() {
  [ -f "$1" ] && source "$1"
}

function source_all_in() {
  if [ -d "$1" ] || [ -d "$(readlink "$1")" ]; then
    for file in "$1"/*.sh; do
      try_to_source "$file" || source_all_in "$file"
    done
    return 0
  else
    return 1
  fi
}

function prepend_path() {
  if [ -d "$1" ]; then
    export PATH="$1:$PATH"
  fi
}

source_all_in "${HOME}/.bashrc.d"

# vim: ft=sh
