" ** looks **
set number
set cursorline
set ruler
set laststatus=2
set list
set listchars=tab:￫\ 

" ** operation **
set incsearch
set hlsearch
" set backspace=indent,start

" ** tab setting **
set expandtab " タブキーでスペースを入力/禁止
set tabstop=4     " タブ文字の表示幅
set shiftwidth=2  " インデント幅
set softtabstop=2 " expandtabするときのスペースの量
set autoindent

" ** colorize **
set modeline modelines=4
syntax enable
