
" looks
set number
set cursorline
set ruler

" operation
set incsearch
set hlsearch
set backspace=indent,eol,start
set clipboard+=unnamed

" tab setting
set expandtab
set tabstop=2 shiftwidth=2 softtabstop=2
set autoindent

" colorize
set modeline modelines=4
syntax enable


if isdirectory( expand("~/.vim/bundle/neobundle.vim")  )
  " Note: Skip initialization for vim-tiny or vim-small.
  if !1 | finish | endif

  if has('vim_starting')
    if &compatible
      set nocompatible               " Be iMproved
    endif

    " Required:
    set runtimepath+=~/.vim/bundle/neobundle.vim/
  endif

  " Required:
  call neobundle#begin(expand('~/.vim/bundle/'))

  " Let NeoBundle manage NeoBundle
  " Required:
  NeoBundleFetch 'Shougo/neobundle.vim'

  " My Bundles here:
  " Refer to |:NeoBundle-examples|.
  " Note: You don't set neobundle setting in .gvimrc!

  NeoBundle 'editorconfig/editorconfig-vim'
  NeoBundle 'derekwyatt/vim-scala'
  NeoBundle 'rust-lang/rust.vim'
  NeoBundle 'zah/nimrod.vim'
  NeoBundle 'cespare/vim-toml'
  NeoBundle 'kana/vim-filetype-haskell'
  NeoBundle 'elixir-lang/vim-elixir'
  NeoBundle 'rhysd/vim-crystal'
  NeoBundle 'fatih/vim-go'

  NeoBundle 'szw/vim-tags'

  call neobundle#end()

  " Required:
  filetype plugin indent on

  " If there are uninstalled bundles found on startup,
  " this will conveniently prompt you to install them.
  NeoBundleCheck
endif
